# ChatParty Configuaration File
# invertP: Send a message to the public with /p <message> when party chat is toggled
# toggleWithP: Toggle the party chat when /p without arguments is entered (not newbie-friendly)
# messageColor: Color of the plugin messages
# chatFormat: Format of the party chat messages. Placeholders: {PARTYNAME}, {DISPLAYNAME}, {MESSAGE}
messageColor: '&a'
adminMessageColor: '&b'
partyChatFormat: '&a[P] &f{DISPLAYNAME}&a: {MESSAGE}'
adminChatFormat: '&b[A] &f{DISPLAYNAME}&b: {MESSAGE}'
invertP: false
toggleWithP: false
players: {}
parties: {}
spy: []